### ISSUE TITLE
[dglo on 2009-11-10 15:23:06] : pDAQ: eventBuilder - handle IOExceptions better

### ISSUE THREAD

**Issue by dglo** [dglo/StringHub#109]
Run 114787 generated a 38GB log file.  The filesystem was read-only, so EventBuilderBackEnd logged an exception for every event:

eventBuilder icecube.daq.eventBuilder.backend.EventBuilderBackEnd-EventWriter ERROR [2009-11-08 03:46:10.697] Could not dispatch event
icecube.daq.io.DispatchException: java.io.IOException: Read-only file system
	at icecube.daq.io.FileDispatcher.dispatchEvent(FileDispatcher.java:184)
	at icecube.daq.io.FileDispatcher.dispatchEvent(FileDispatcher.java:216)
	at icecube.daq.eventBuilder.backend.EventBuilderBackEnd$OutputThread.sendToDaqDispatch(EventBuilderBackEnd.java:1201)
	at icecube.daq.eventBuilder.backend.EventBuilderBackEnd$OutputThread.run(EventBuilderBackEnd.java:1158)
	at java.lang.Thread.run(Thread.java:735)
Caused by: java.io.IOException: Read-only file system
	at sun.nio.ch.FileDispatcher.write0(Native Method)
	at sun.nio.ch.FileDispatcher.write(FileDispatcher.java:51)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:104)
	at sun.nio.ch.IOUtil.write(IOUtil.java:75)
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:206)
	at icecube.daq.io.FileDispatcher.dispatchEvent(FileDispatcher.java:179)
	... 4 more

**Comment by dglo** [comment]
[dglo on 2010-01-24 12:39:26]
-- If the eventBuilder filesystem goes read-only, kill the detector
Sending        StringHub/src/main/java/icecube/daq/sender/RequestReader.java
Sending        StringHub/src/main/java/icecube/daq/sender/Sender.java
Sending        StringHub/src/test/java/icecube/daq/sender/SenderTest.java
Sending        daq-integration-test/src/test/java/icecube/daq/test/DAQTestUtil.java
Adding         daq-integration-test/src/test/java/icecube/daq/test/EBReadonlyTest.java
Sending        daq-integration-test/src/test/java/icecube/daq/test/MockDispatcher.java
Sending        daq-integration-test/src/test/java/icecube/daq/test/RequestToDataBridge.java
Adding         daq-integration-test/src/test/resources/config/trigger/in-ice-mbt-5.xml
Sending        daq-io/src/main/java/icecube/daq/io/Dispatcher.java
Sending        daq-io/src/main/java/icecube/daq/io/PayloadReader.java
Sending        daq-request-filler/src/main/java/icecube/daq/reqFiller/RequestFiller.java
Sending        eventBuilder-prod/src/main/java/icecube/daq/eventBuilder/GlobalTriggerReader.java
Sending        eventBuilder-prod/src/main/java/icecube/daq/eventBuilder/SPDataAnalysis.java
Sending        eventBuilder-prod/src/main/java/icecube/daq/eventBuilder/backend/EventBuilderBackEnd.java
Sending        eventBuilder-prod/src/main/java/icecube/daq/eventBuilder/backend/SPDataProcessor.java
Sending        eventBuilder-prod/src/test/java/icecube/daq/eventBuilder/backend/EventBuilderBackEndTest.java
Sending        eventBuilder-prod/src/test/java/icecube/daq/eventBuilder/test/MockDispatcher.java
Committed revision 4863.
