### ISSUE TITLE
[dglo on 2014-06-03 11:09:35] : pDAQ: Get rid of "Aborting sort thread" stack traces at the end of hitspool runs

### ISSUE THREAD

**Issue by dglo** [dglo/StringHub#213]
Hit spool runs end with a whole slew of:

stringHub#29 icecube.daq.bindery.MultiChannelMergeSort-MultiChannelMergeSort-g ERROR [2014-06-02 18:38:06.2180000000] Aborting sort thread
java.lang.IndexOutOfBoundsException
        at java.nio.Buffer.checkIndex(Buffer.java:538)
        at java.nio.HeapByteBuffer.getLong(HeapByteBuffer.java:410)
        at icecube.daq.stringhub.FilesHitSpool.consume(FilesHitSpool.java:144)
        at icecube.daq.bindery.MultiChannelMergeSort.run(MultiChannelMergeSort.java:168)

Having to wade through ~100 copies of this while trying to determine why a run ended badly is *REALLY* annoying.

**Comment by dglo** [comment]
[dglo on 2014-06-03 11:10:25]
svn commit -m"Issue 6974: Silence \"Aborting sort thread\" stacktraces at end of hitspool runs" StringHub/src/main/java/icecube/daq/stringhub/FilesHitSpool.java
Sending        StringHub/src/main/java/icecube/daq/stringhub/FilesHitSpool.java
Transmitting file data .
Committed revision 15021.

**Comment by dglo** [comment]
[dglo on 2014-08-14 11:26:30]
Time to close these issues; Hinterland is ready to be released
