### ISSUE TITLE
[tbendfelt on 2015-10-19 15:07:18] : pDAQ: StringHub - Softbooting stalled DOMS at run start is broken

### ISSUE THREAD

**Issue by dglo** [dglo/StringHub#269]
At startup, DataCollector is designed to soft boot DOMS that are not running DOMapp.  As of the Karben4 release, if the watchdog fires while the DOM is being tested, the DOM will be dropped even though the soft boot is a success.

A typical failure mode for DOMS is for them to become non-responsive while running DOMApp.  In this case, the initialization routine needs the watchdog to implement a timeout/interrupt, but this should not result in a dropped DOM.

**Comment by dglo** [comment]
[tbendfelt on 2015-10-19 15:11:25]
See issue 7423 which documents a primary use case.  In this scenario, power cycling a subset of DOMS on a string damages pre-existing DOMapp communications.  Normally, this would result in an automatic soft boot of the DOMS, but with this defect it results in the entire string dropping.

**Comment by dglo** [comment]
[tbendfelt on 2016-02-03 13:41:36]
During initialization the watchdog is placed in a non-fatal mode.  This allows the dom to be soft booted to correct any recoverable conditions.

$ svn log -v -r15979:15981
------------------------------------------------------------------------
r15979 | bendfelt | 2016-02-03 13:15:00 -0600 (Wed, 03 Feb 2016) | 1 line
Changed paths:
   M /projects/StringHub/trunk/src/main/java/icecube/daq/domapp/LegacyDataCollector.java
   M /projects/StringHub/trunk/src/main/java/icecube/daq/domapp/NewDataCollector.java
   M /projects/StringHub/trunk/src/main/java/icecube/daq/domapp/dataacquisition/Watchdog.java

Issue 7592: Enhance the watchdog with an increasable timeout and non-fatal timeout mode.
------------------------------------------------------------------------
r15980 | bendfelt | 2016-02-03 13:23:20 -0600 (Wed, 03 Feb 2016) | 1 line
Changed paths:
   M /projects/StringHub/trunk/src/main/java/icecube/daq/domapp/dataacquisition/DataAcquisition.java

Issue 7592: Set the watchdog to interrupt-only during initialization of domapp, also handle exceptions from domapp query such as the BufferOverflow that follows a run stopped mid-interval
------------------------------------------------------------------------
r15981 | bendfelt | 2016-02-03 13:36:29 -0600 (Wed, 03 Feb 2016) | 1 line
Changed paths:
   M /projects/StringHub/trunk/src/main/java/icecube/daq/Omicron.java

Issue 7592,7689: Use async consumer for hit data, also shutdown troubled collectors without resorting to interupting.
------------------------------------------------------------------------

**Comment by dglo** [comment]
[tbendfelt on 2016-02-04 16:47:26]
Bug Fix:

This can happen:

31368 [60B] WARN  icecube.daq.domapp.dataacquisition.DataAcquisition  - DOM is not responding to DOMApp query - will attempt to softboot
java.io.FileNotFoundException: /dev/dhc6w0dB (Resource temporarily unavailable)
	at java.io.RandomAccessFile.open(Native Method)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:241)
	at icecube.daq.domapp.DOMIO.<init>(DOMIO.java:28)
	at icecube.daq.domapp.DOMApp.<init>(DOMApp.java:35)
	at icecube.daq.domapp.dataacquisition.DataAcquisition.doInitialization(DataAcquisition.java:634)
	at icecube.daq.domapp.NewDataCollector.launch_runcore(NewDataCollector.java:385)
	at icecube.daq.domapp.NewDataCollector.run(NewDataCollector.java:350)
31379 [60B] ERROR icecube.daq.domapp.NewDataCollector  - Intercepted error in DataCollector runcore
icecube.daq.domapp.dataacquisition.AcquisitionError: Error while initializing [60B]
	at icecube.daq.domapp.dataacquisition.DataAcquisition.doInitialization(DataAcquisition.java:699)
	at icecube.daq.domapp.NewDataCollector.launch_runcore(NewDataCollector.java:385)
	at icecube.daq.domapp.NewDataCollector.run(NewDataCollector.java:350)
Caused by: java.lang.NullPointerException
	at icecube.daq.domapp.dataacquisition.DataAcquisition.doInitialization(DataAcquisition.java:664)
	... 2 more


------------------------------------------------------------------------
r15984 | bendfelt | 2016-02-04 16:44:02 -0600 (Thu, 04 Feb 2016) | 1 line
Changed paths:
   M /projects/StringHub/trunk/src/main/java/icecube/daq/domapp/dataacquisition/DataAcquisition.java

Issue 7592: Guard against driver issues that hamper the creation of the DOMApp instance.
------------------------------------------------------------------------

**Comment by dglo** [comment]
[tbendfelt on 2016-02-18 15:53:13]
Enhancement:

Noticing that soft booting can take some time.

 svn log -v -r15998
------------------------------------------------------------------------
r15998 | bendfelt | 2016-02-18 15:47:59 -0600 (Thu, 18 Feb 2016) | 1 line
Changed paths:
   M /projects/StringHub/trunk/src/main/java/icecube/daq/domapp/dataacquisition/DataAcquisition.java

Issue 7592: Use a custom watchdog timeout for softbooting phase.
------------------------------------------------------------------------
