### ISSUE TITLE
[tbendfelt on 2016-07-19 10:25:46] : pDAQ: StringHub - DOM device file not closed after IO Error

### ISSUE THREAD

**Issue by dglo** [dglo/StringHub#296]
DataCollector does not close the device file on exception paths.  This can be vexing to the dor driver which has take care to generate an IO Error in order to tell StringHub to close the device. 

Example:

19624278 [2016-07-19 04:38:34,643] [40A] ERROR icecube.daq.domapp.NewDataCollector  - Intercepted error in DataCollector runcore
icecube.daq.domapp.dataacquisition.AcquisitionError: Error acquiring data from [40A]
    at icecube.daq.domapp.dataacquisition.DataAcquisition.doIntervalWithTcal(DataAcquisition.java:612)
    at icecube.daq.domapp.NewDataCollector.runcore(NewDataCollector.java:524)
    at icecube.daq.domapp.NewDataCollector.launch_runcore(NewDataCollector.java:441)
    at icecube.daq.domapp.NewDataCollector.run(NewDataCollector.java:380)
Caused by: DOM Message exception: sent type = GET_DATA wrapped exception is java.io.IOException: Input/output error
    at icecube.daq.domapp.DOMApp.recvMessage(DOMApp.java:480)
    at icecube.daq.domapp.dataacquisition.DataAcquisition.doIntervalWithTcal(DataAcquisition.java:541)
    ... 3 more
Caused by: java.io.IOException: Input/output error
    at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
    at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46)
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
    at sun.nio.ch.IOUtil.read(IOUtil.java:192)
    at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:159)
    at icecube.daq.domapp.DOMIO.recv(DOMIO.java:85)
    at icecube.daq.domapp.DOMApp.recvMessage(DOMApp.java:465)
    ... 4 more

Which leads to a repeating error in the kernel log until the process is killed:

Jul 19 04:38:47 scube kernel: dh_timer: inq queue is full, checking for stuck acks
Jul 19 04:38:47 scube kernel: dh_timer: inq queue is full, checking for stuck acks
Jul 19 04:38:47 scube kernel: dh_timer: inq queue is full, checking for stuck acks
Jul 19 04:38:47 scube kernel: dh_timer: inq queue is full, checking for stuck acks
Jul 19 04:38:47 scube kernel: dh_timer: inq queue is full, checking for stuck acks
Jul 19 04:38:47 scube kernel: dh_timer: inq queue is full, checking for stuck acks
Jul 19 04:38:47 scube kernel: dh_timer: inq queue is full, checking for stuck acks
Jul 19 04:38:47 scube kernel: dh_timer: inq queue is full, checking for stuck acks
Jul 19 04:38:47 scube kernel: dh_timer: inq queue is full, checking for stuck asks
...

**Comment by dglo** [comment]
[tbendfelt on 2016-08-02 11:41:50]
svn log -v -r16189
------------------------------------------------------------------------
r16189 | bendfelt | 2016-08-02 11:40:00 -0500 (Tue, 02 Aug 2016) | 1 line
Changed paths:
   M /projects/StringHub/trunk/src/main/java/icecube/daq/domapp/LegacyDataCollector.java
   M /projects/StringHub/trunk/src/main/java/icecube/daq/domapp/NewDataCollector.java

Issue 7878:  Close the DOM device file on exit.
------------------------------------------------------------------------
