### ISSUE TITLE
[tbendfelt on 2016-07-21 17:12:43] : pDAQ: StringHub - Datacollector too eager to avoid softboot on startup

### ISSUE THREAD

**Issue by dglo** [dglo/StringHub#298]
Corrupt instances of DOMAPP are making it past the softboot check.

The soft boot checks consider DOMAPP as heathy based on a successful call to app.isRunningDOMApp(), unfortunately this call can succeed and the following calls to  app.endRun() and  app.getMainboardID() can fail. This does not lead to a softboot.  The DOM is just dropped.  Instead, a soft boot should be attempted on the first occurance. 

Currently presenting as:

CnCServer icecube.daq.domapp.dataacquisition.DataAcquisition-01B WARN [2016-07-21 21:18:47.5770000000] DOM is not responding to DOMApp query - will attempt to softboot
DOM Message exception: sent type = GET_DOM_ID wrapped exception is java.nio.channels.ClosedChannelException
        at icecube.daq.domapp.DOMApp.sendMessage(DOMApp.java:535)
        at icecube.daq.domapp.DOMApp.sendMessage(DOMApp.java:440)
        at icecube.daq.domapp.DOMApp.getMainboardID(DOMApp.java:296)
        at icecube.daq.domapp.dataacquisition.DataAcquisition.doInitialization(DataAcquisition.java:655)
        at icecube.daq.domapp.NewDataCollector.launch_runcore(NewDataCollector.java:396)
        at icecube.daq.domapp.NewDataCollector.run(NewDataCollector.java:361)
Caused by: java.nio.channels.ClosedChannelException
        at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110)
        at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:199)
        at icecube.daq.domapp.DOMIO.send(DOMIO.java:57)
        at icecube.daq.domapp.DOMApp.sendMessage(DOMApp.java:517)
        ... 5 more
CnCServer icecube.daq.domapp.NewDataCollector-01B ERROR [2016-07-21 21:18:47.5880000000] Intercepted error in DataCollector runcore
java.lang.IllegalArgumentException: Attempt to change mbid from [a490e191a5a0] to [null]
        at icecube.daq.domapp.NewDataCollector.setMainboardID(NewDataCollector.java:225)
        at icecube.daq.domapp.NewDataCollector.launch_runcore(NewDataCollector.java:400)
        at icecube.daq.domapp.NewDataCollector.run(NewDataCollector.java:361)

Additional Information: The relevant code from DataAcquisition.java and LegacyDataCollector.java:

 if (!alwaysSoftboot)
            {
                logger.debug("Autodetecting DOMApp");
                try
                {
                    app = new DOMApp(card, pair, dom);
                    if (app.isRunningDOMApp())
                    {
                        needSoftboot = false;  <----- TOO SOON!!
                        try
                        {
                            app.endRun();
                        }
                        catch (MessageException mex)
                        {
                            // this is normally what one would expect from a
                            // DOMApp not currently in running mode, ignore
                        }
                        reportedMBID = app.getMainboardID();
                    }
                    else
                    {
                        app.close();
                        app = null;
                    }
                }
                catch (Exception ex)
                {
                    // The watchdog may have fired, or domapp may have responded
                    // inconsistently such as when the previous run exited
                    // mid-interval
                    //
                    logger.warn("DOM is not responding to DOMApp query -" +
                            " will attempt to softboot", ex);

                    if(app != null)
                    {
                        app.close();
                        app = null;
                    }

                    // The watchdog may have fired, reset the interrupt.
                    Thread.currentThread().interrupted();
                    watchdog.ping();
                }

**Comment by dglo** [comment]
[tbendfelt on 2016-08-02 13:29:01]
svn log -v -r16190
------------------------------------------------------------------------
r16190 | bendfelt | 2016-08-02 13:28:00 -0500 (Tue, 02 Aug 2016) | 1 line
Changed paths:
   M /projects/StringHub/trunk/src/main/java/icecube/daq/domapp/LegacyDataCollector.java
   M /projects/StringHub/trunk/src/main/java/icecube/daq/domapp/dataacquisition/DataAcquisition.java

Issue 7882:  Expand auto-softboot check to include failed mbid calls.
------------------------------------------------------------------------
