### ISSUE TITLE
[dglo on 2016-08-12 13:47:04] : pDAQ: StringHub - hitspool DB problems

### ISSUE THREAD

**Issue by dglo** [dglo/StringHub#300]
Runs on SPTS occasionally fail because of SQLite contention.  icecube.daq.stringhub.Metadata should synchronize access to the file.

See http://stackoverflow.com/questions/13891006/getting-sqlite-busy-database-file-is-locked-with-select-statements

One run on SPTS showed this:

stringHub#7 icecube.daq.stringhub.Metadata-hit-consumer ERROR [2016-08-12 18:09:
37.6020000000] Cannot insert metadata (filename HitSpool-598.dat [194189740487776946-194189890487776945])
java.sql.SQLException: [SQLITE_BUSY]  The database file is locked (database is locked)
        at org.sqlite.core.DB.newSQLException(DB.java:890)
        at org.sqlite.core.DB.newSQLException(DB.java:901)
        at org.sqlite.core.DB.execute(DB.java:807)
        at org.sqlite.core.DB.executeUpdate(DB.java:847)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:86)
        at icecube.daq.stringhub.Metadata.write(Metadata.java:135)
        at icecube.daq.stringhub.FileBundle.openNewFile(FilesHitSpool.java:449)
        at icecube.daq.stringhub.FileBundle.write(FilesHitSpool.java:518)
...

**Comment by dglo** [comment]
[dglo on 2016-08-17 10:43:50]
svn commit -m"Issue 7890: Synchronize public methods; SQLite is not multi-thread-friendly" src/main/java/icecube/daq/stringhub/Metadata.java
Sending        src/main/java/icecube/daq/stringhub/Metadata.java
Transmitting file data .done
Committing transaction...
Committed revision 16200.
