### ISSUE TITLE
[dglo on 2007-06-14 20:43:16] : pDAQ: StringHub - IllegalArgumentException

### ISSUE THREAD

**Issue by dglo** [dglo/StringHub#31]
In SPS run 108700, there's this stack trace in stringHub-60.log:

java.lang.IllegalArgumentException
 at java.nio.Buffer.limit(Buffer.java:249)
 at icecube.daq.domapp.DataCollector.dataProcess(DataCollector.java:456)
 at icecube.daq.domapp.DataCollector.runcore(DataCollector.java:821)
 at icecube.daq.domapp.DataCollector.run(DataCollector.java:696)
Intercepted error in DataCollector runcore: java.lang.IllegalArgumentException

**Comment by dglo** [comment]
[dglo on 2007-06-14 21:04:37]
Also in run 108701 stringHub-66.log:

java.lang.IllegalArgumentException
        at java.nio.Buffer.limit(Buffer.java:249)
        at icecube.daq.domapp.DataCollector.dataProcess(DataCollector.java:456)
        at icecube.daq.domapp.DataCollector.runcore(DataCollector.java:821)
        at icecube.daq.domapp.DataCollector.run(DataCollector.java:696)
Intercepted error in DataCollector runcore: java.lang.IllegalArgumentException

**Comment by dglo** [comment]
[kaeld on 2007-07-12 11:27:41]
Added code to dump out what is happening during the Alpaca dropouts.  Apparently something is getting corrupted in the data buffers - either in the DOM, in transit, or in the StringHub - don't know yet.  It is remarkable that the messages with the errors ALWAYS occur not as the 1st record in the returned buffer from the DOM but some follow-on record.  The record has the correct DOMApp signature (type 0x90) but the contained data looks to be absolute junk.  Recommend taking Alpaca out of the configuration for further study with low-level tools.

**Comment by dglo** [comment]
[kaeld on 2007-07-12 11:30:14]
Checking in 1737 DataCollector.java which re-throws the exception - this was causing bad data to get downstream.

**Comment by dglo** [comment]
[kaeld on 2007-07-12 12:39:26]
don't know why this is throwing the exceptions- need some debug data on this.
