### ISSUE TITLE
[tbendfelt on 2016-11-08 10:15:17] : pDAQ: StringHub - RecordBufferIndexTest fails occasionally

### ISSUE THREAD

**Issue by dglo** [dglo/StringHub#318]
Infrequent but repeatable test failures:

java.lang.AssertionError: #0: pos 0 != -1 last -1 val 843527548476054307 [ArrayListIndex:[[28, 847219308072655773][80, 849237518666661060][135, 851623690696776707]...
	at org.junit.Assert.fail(Assert.java:88)
	at icecube.daq.performance.binary.buffer.RecordBufferIndexTest.checkIndex(RecordBufferIndexTest.java:404)
	at icecube.daq.performance.binary.buffer.RecordBufferIndexTest.checkUpdateIndex(RecordBufferIndexTest.java:449)
	at icecube.daq.performance.binary.buffer.RecordBufferIndexTest.testArrayListIndex2(RecordBufferIndexTest.java:213)

**Comment by dglo** [comment]
[tbendfelt on 2016-11-08 10:56:33]
Test had a defect.

svn log -v -r 16327
------------------------------------------------------------------------
r16327 | bendfelt | 2016-11-08 10:38:29 -0600 (Tue, 08 Nov 2016) | 1 line
Changed paths:
   M /projects/StringHub/trunk/src/test/java/icecube/daq/performance/binary/buffer/RecordBufferIndexTest.java

Issue 7966:  Test was failing when randomly generated positions produced a duplicate.
------------------------------------------------------------------------

svn log -v -r 16328
------------------------------------------------------------------------
r16328 | bendfelt | 2016-11-08 10:56:11 -0600 (Tue, 08 Nov 2016) | 1 line
Changed paths:
   M /projects/StringHub/trunk/src/test/java/icecube/daq/performance/binary/buffer/RecordBufferIndexTest.java

Issue 7966 Fixed another test defect based on random number generating a zero value.
------------------------------------------------------------------------\n\n
