### ISSUE TITLE
[tbendfelt on 2016-11-08 11:29:11] : pDAQ: StringHub - ExpandingMemoryRecordStoreTest fails occasionally

### ISSUE THREAD

**Issue by dglo** [dglo/StringHub#319]
Ocasional failures:

testPrune(icecube.daq.performance.binary.store.impl.ExpandingMemoryRecordStoreTest)  Time elapsed: 0.006 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1000> but was:<1100>
       at org.junit.Assert.fail(Assert.java:88)
       at org.junit.Assert.failNotEquals(Assert.java:743)
       at org.junit.Assert.assertEquals(Assert.java:118)
       at org.junit.Assert.assertEquals(Assert.java:555)
       at org.junit.Assert.assertEquals(Assert.java:542)
       at icecube.daq.performance.binary.store.impl.ExpandingMemoryRecordStoreTest.testPrune(ExpandingMemoryRecordStoreTest.java:102)

and:

	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at icecube.daq.performance.binary.test.Assertions.assertContainsAtLeast(Assertions.java:122)
	at icecube.daq.performance.binary.store.impl.ExpandingMemoryRecordStoreTest.testOverlapingForEach(ExpandingMemoryRecordStoreTest.java:336)
	at icecube.daq.performance.binary.store.impl.ExpandingMemoryRecordStoreTest.testOverlapingForEach(ExpandingMemoryRecordStoreTest.java:265)

and:

testOverlapingQuery(icecube.daq.performance.binary.store.impl.ExpandingMemoryRecordStoreTest)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.AssertionError:
       at org.junit.Assert.fail(Assert.java:88)
       at org.junit.Assert.assertTrue(Assert.java:41)
       at icecube.daq.performance.binary.test.Assertions.assertContainsAtLeast(Assertions.java:95)
       at icecube.daq.performance.binary.store.impl.ExpandingMemoryRecordStoreTest.testOverlapingQuery(ExpandingMemoryRecordStoreTest.java:252)
       at icecube.daq.performance.binary.store.impl.ExpandingMemoryRecordStoreTest.testOverlapingQuery(ExpandingMemoryRecordStoreTest.java:189)

**Comment by dglo** [comment]
[tbendfelt on 2016-11-08 16:34:06]
There were two defects in the test. One was bad accounting for messages that exactly filled a segment and the other was assuming random values did not repeat across the segments.

svn log -v -r 16331:16332
------------------------------------------------------------------------
r16331 | bendfelt | 2016-11-08 16:30:27 -0600 (Tue, 08 Nov 2016) | 1 line
Changed paths:
   M /projects/StringHub/trunk/src/test/java/icecube/daq/performance/binary/test/RandomOrderedValueSequence.java

Issue 7967:  Add function for generating non-duplicating sequence members.
------------------------------------------------------------------------
r16332 | bendfelt | 2016-11-08 16:31:48 -0600 (Tue, 08 Nov 2016) | 1 line
Changed paths:
   M /projects/StringHub/trunk/src/test/java/icecube/daq/performance/binary/store/impl/ExpandingMemoryRecordStoreTest.java

Issue 7967: Fixed test that failed when values repeated or when messages filled a whole segment.
------------------------------------------------------------------------
