### ISSUE TITLE
[tbendfelt on 2016-12-27 01:37:38] : pDAQ: StringHub - DataCollector no longer tolerant to IO errors during TCal operations

### ISSUE THREAD

**Issue by dglo** [dglo/StringHub#326]
An optimization in potosi relocated (the position in code) the tcal operation.  The new position is not trapping and ignoring IOExceptions like the old position was.  The result is that StringHub is not tolerant of occasional occasional cal errors.

We see IO errors sporadically on many doms, but regularly on (38-49, 38-50 and 74-10).  These doms will experience chronic dropping.

The exception trap needs to be put back in place in the new code .

**Comment by dglo** [comment]
[tbendfelt on 2016-12-27 01:48:01]
From run 128976:

stringHub#38 - - [2016-12-27 06:58:32.525480] Start of log at LOG=log(10.1.2.20:9012)
stringHub#38 - - [2016-12-27 06:58:32.691422] Version info: Potosi_rc1 14222:143282 2016-12-06 18:17:42
stringHub#38 icecube.daq.domapp.DataCollector-60A ERROR [2016-12-27 06:58:46.110] Intercepted error in DataCollector runcore
icecube.daq.domapp.dataacquisition.AcquisitionError: Error acquiring data from [60A]
        at icecube.daq.domapp.dataacquisition.DataAcquisition.doInterval(DataAcquisition.java:527)
        at icecube.daq.domapp.DataCollector.runcore(DataCollector.java:506)
        at icecube.daq.domapp.DataCollector.launch_runcore(DataCollector.java:420)
        at icecube.daq.domapp.DataCollector.run(DataCollector.java:359)
Caused by: icecube.daq.domapp.dataacquisition.AcquisitionError: IO Error performing a tcal on [60A]
        at icecube.daq.domapp.dataacquisition.DataAcquisition.doTCAL(DataAcquisition.java:806)
        at icecube.daq.domapp.dataacquisition.DataAcquisition.doInterval(DataAcquisition.java:520)
        ... 3 more
Caused by: java.io.IOException: TCAL read failed.
        at icecube.daq.dor.Driver.readTCAL(Driver.java:282)
        at icecube.daq.domapp.dataacquisition.DataAcquisition.doTCAL(DataAcquisition.java:772)
        ... 4 more

stringHub#38 icecube.daq.domapp.DataCollector-60B ERROR [2016-12-27 06:59:16.198] Intercepted error in DataCollector runcore
icecube.daq.domapp.dataacquisition.AcquisitionError: Error acquiring data from [60B]
        at icecube.daq.domapp.dataacquisition.DataAcquisition.doInterval(DataAcquisition.java:527)
        at icecube.daq.domapp.DataCollector.runcore(DataCollector.java:506)
        at icecube.daq.domapp.DataCollector.launch_runcore(DataCollector.java:420)
        at icecube.daq.domapp.DataCollector.run(DataCollector.java:359)
Caused by: icecube.daq.domapp.dataacquisition.AcquisitionError: IO Error performing a tcal on [60B]
        at icecube.daq.domapp.dataacquisition.DataAcquisition.doTCAL(DataAcquisition.java:806)
        at icecube.daq.domapp.dataacquisition.DataAcquisition.doInterval(DataAcquisition.java:520)
        ... 3 more
Caused by: java.io.IOException: TCAL read failed.
        at icecube.daq.dor.Driver.readTCAL(Driver.java:282)
        at icecube.daq.domapp.dataacquisition.DataAcquisition.doTCAL(DataAcquisition.java:772)
        ... 4 more

**Comment by dglo** [comment]
[tbendfelt on 2017-01-03 11:41:02]
Fixed.

svn log -v -r16415:16416
------------------------------------------------------------------------
r16415 | bendfelt | 2017-01-03 11:38:48 -0600 (Tue, 03 Jan 2017) | 1 line
Changed paths:
   M /projects/StringHub/trunk/src/main/java/icecube/daq/domapp/dataacquisition/DataAcquisition.java

Issue 8027: Ignore tcal acquisition errors. Transient IO errors should not doom the channel.
------------------------------------------------------------------------
r16416 | bendfelt | 2017-01-03 11:40:06 -0600 (Tue, 03 Jan 2017) | 1 line
Changed paths:
   M /projects/StringHub/trunk/src/main/java/icecube/daq/domapp/DataCollector.java

Issue 8027: Remove wrapper tcal methods and call directly into acquisition class methods.
------------------------------------------------------------------------
