### ISSUE TITLE
[tbendfelt on 2017-01-04 10:37:55] : pDAQ: StringHub - Bad HLC hit count reporting in potosi release

### ISSUE THREAD

**Issue by dglo** [dglo/StringHub#329]
See attached screenshot of mini hlc rate for run 128977.

StringHub is occasionally reporting bad HLC hit counts which causes the defective graph.  The issue is rooted in the potosi release change to report HLC hits to the run monitor in batches of 100 rather than 1-by-1. If a very low HLC rate DOM is in play, the run monitor will see some HLC counts way way later than the bin they belong to leading to a bad monitor message and the discarding of most of the tardy counts. 

See 128977-bad-hlc-moni-string-1.txt. Whenever the RunMonitor see's a late batch, it kicks out a bin with a bad recordingStartTime field, and then drops some of the remaining hits with this error:

stringHub#1 icecube.daq.monitoring.QueueConsumer-RunMonitor ERROR [2016-12-27 16:01:32.056] icecube.daq.monitoring.HLCCountConsumer cannot process [312294925731164634, ..., 312480909652142342]@5318524a79f4
java.lang.Error: Previous bin has not been cleared!  Previous=Bin[312294925731164634-312300000000000000: Counter=3], active=Bin[312300000000000000-312306000000000000: Counter=1], index=312307919691454815
	at icecube.daq.monitoring.BinManager.get(BinManager.java:167)
	at icecube.daq.monitoring.BinnedQueueConsumer.getContainer(BinnedQueueConsumer.java:135)
	at icecube.daq.monitoring.HLCCountConsumer.process(RunMonitor.java:437)
	at icecube.daq.monitoring.HLCCountConsumer.process(RunMonitor.java:321)
	at icecube.daq.monitoring.QueueConsumer.processHeldValue(QueueConsumer.java:107)
	at icecube.daq.monitoring.RunMonitor.mainloop(RunMonitor.java:1517)
	at icecube.daq.monitoring.ThreadDaemon.run(RunMonitor.java:1171)
	at icecube.daq.monitoring.RunMonitor.run(RunMonitor.java:1225)
	at java.lang.Thread.run(Thread.java:745)

**Comment by dglo** [comment]
[tbendfelt on 2017-01-10 15:22:04]
Fixed in two parts.

Part I:  Make the batching of HLC hit reporting time-sensitive with respect to the delay of hit reporting.
Part II: Make HLC consumer (A binned consumer) resistent to hits reported after the expiration of the bin.

Part I:
svn log -v -r 16419:16420
------------------------------------------------------------------------
r16419 | bendfelt | 2017-01-06 14:57:54 -0600 (Fri, 06 Jan 2017) | 1 line
Changed paths:
   M /projects/StringHub/trunk/src/main/java/icecube/daq/domapp/dataprocessor/DataStats.java

Issue 8031: Ensure that HLC hits are reported within a minute of receipt. This ensures that the report client can manage 10 minute hit binning across DOMs of different rates.
------------------------------------------------------------------------
r16420 | bendfelt | 2017-01-06 14:59:50 -0600 (Fri, 06 Jan 2017) | 1 line
Changed paths:
   A /projects/StringHub/trunk/src/test/java/icecube/daq/domapp/dataprocessor/DataStatsTest.java

Issue 8031: Introduce test class for DataStats.java.
------------------------------------------------------------------------

Part II:

Test cases:
svn log -v -r 16421
------------------------------------------------------------------------
r16421 | bendfelt | 2017-01-06 17:42:40 -0600 (Fri, 06 Jan 2017) | 1 line
Changed paths:
   M /projects/StringHub/trunk/src/test/java/icecube/daq/monitoring/BinnedQueueConsumerTest.java

Issue 8028: Add tests cases for delayed channels.
------------------------------------------------------------------------

Manage pathological late channel cases:
svn log -v -r 16423:16425
------------------------------------------------------------------------
r16423 | bendfelt | 2017-01-10 11:13:20 -0600 (Tue, 10 Jan 2017) | 1 line
Changed paths:
   M /projects/StringHub/trunk/src/main/java/icecube/daq/monitoring/BinManager.java

Issue 8031: Fix Bin index X is less than active start index Y error.
------------------------------------------------------------------------
r16424 | bendfelt | 2017-01-10 13:18:50 -0600 (Tue, 10 Jan 2017) | 1 line
Changed paths:
   M /projects/StringHub/trunk/src/main/java/icecube/daq/monitoring/BinnedQueueConsumer.java
   M /projects/StringHub/trunk/src/main/java/icecube/daq/monitoring/RunMonitor.java
   M /projects/StringHub/trunk/src/test/java/icecube/daq/monitoring/BinnedQueueConsumerTest.java

Issue 8031: BinnedQueueConsumer now rejects samples with a value earlier than the last reported bin.
------------------------------------------------------------------------
r16425 | bendfelt | 2017-01-10 14:36:27 -0600 (Tue, 10 Jan 2017) | 1 line
Changed paths:
   M /projects/StringHub/trunk/src/main/java/icecube/daq/monitoring/BinnedQueueConsumer.java
   M /projects/StringHub/trunk/src/test/java/icecube/daq/monitoring/BinnedQueueConsumerTest.java

Issue 8031: Allow overlapping bins across switch runs spans.
------------------------------------------------------------------------\n\n

**Comment by dglo** [comment]
[tbendfelt on 2017-01-10 15:31:04]
Fixed with a light hand to de-risk the potosi_rc2 release. Added Issue 8040 to suggest more comprehensive fixes later.
