### ISSUE TITLE
[tbendfelt on 2017-05-22 10:58:42] : pDAQ: StringHub - Lower the sensitivity to dropped NTP requests

### ISSUE THREAD

**Issue by dglo** [dglo/StringHub#342]
We see occasional alerts from the clock monitor:

An error occured while accessing the NTP server [ntp1] from [ichub20.sps.icecube.southpole.usap.gov]: [Receive timed out]

It is hard to judge the severity of this alert. It may be a network issue or the NTP server could be overloaded.

Consider load balancing between ntp1 and ntp2
Consider increasing the polling period (5 minutes to 15 minutes?)
Consider a random sleep at full start to stagger the hub requests
Consider logging more context
Consider attempting a 2nd/3rd request before alerting and bypass alert if those are successful.

The purpose of the alert is to detect a sustained issue, not addressing each and every dropped request.

**Comment by dglo** [comment]
[tbendfelt on 2017-06-08 14:12:14]
The errors that have shown up so far (2016 to Jun 2017) is a timeout error.

:: run 129548 hub 37 ::
stringHub#37 icecube.daq.time.monitoring.NTPService-NTP Service-ntp1 WARN [2017-05-26 08:51:15.688] NTP Query Error
java.net.SocketTimeoutException: Receive timed out
        at java.net.PlainDatagramSocketImpl.receive0(Native Method)
        at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:143)
        at java.net.DatagramSocket.receive(DatagramSocket.java:812)
        at org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:92)
        at org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:114)
        at icecube.daq.time.monitoring.NTPService$NTPQueryJob.run(NTPService.java:198)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

stringHub#37 icecube.daq.time.monitoring.ClockAlerter-NTP Service-ntp1 WARN [2017-05-26 08:51:15.717] Problem acquiring from the NTP source: Receive timed out

**Comment by dglo** [comment]
[tbendfelt on 2017-06-08 15:53:26]
Implemented 2 of the suggested ideas: staggering startup and re-trying query that time out.

svn log -v -r16588
------------------------------------------------------------------------
r16588 | bendfelt | 2017-06-08 15:51:02 -0500 (Thu, 08 Jun 2017) | 1 line
Changed paths:
   M /projects/StringHub/trunk/src/main/java/icecube/daq/time/monitoring/NTPService.java

Issue 8128: Reduce nuisance alerts by re-trying the NTP query a few times at time out, also stagger the startup time across  hubs.
------------------------------------------------------------------------

**Comment by dglo** [comment]
[dglo on 2018-01-02 10:55:41]
Sprecher is deployed!
