### ISSUE TITLE
[tbendfelt on 2018-01-04 11:33:13] : pDAQ: StringHub - In-memory hit cache is too small for full production rate

### ISSUE THREAD

**Issue by dglo** [dglo/StringHub#357]
The in-memory hit cache (used by readout code to avoid going to hitspool in the nominal workload) is arbitrarily sized at 512 MB.  The cache size is fixed, but the pruning policy is time based such that the cache must hold 90 seconds of hit data.  This assumption failed during the recent flasher runs and caused a run fail:

stringHub#80 icecube.daq.bindery.AsyncSorterOutput-hit-consumer ERROR [2017-12-30 13:48:06.482] Consumer error:
java.nio.BufferOverflowException
	at icecube.daq.performance.binary.buffer.RecordBuffer$BoundsCheck.ensureWriteAvailable(RecordBuffer.java:321)
	at icecube.daq.performance.binary.buffer.RecordBuffers$FastRingBuffer.put(RecordBuffers.java:994)
	at icecube.daq.performance.binary.store.impl.RingBufferRecordStore.store(RingBufferRecordStore.java:95)
	at icecube.daq.performance.binary.store.impl.SplitStore.store(SplitStore.java:94)
	at icecube.daq.performance.binary.store.RecordStore$SynchronizedStore.store(RecordStore.java:198)
	at icecube.daq.sender.NewSender.consume(NewSender.java:143)
	at icecube.daq.bindery.AsyncSorterOutput.run(AsyncSorterOutput.java:143)
	at java.lang.Thread.run(Thread.java:748)

There are a few options:
1) increase the size of the cache
2) Prune the cache on a size basis rather than time basis
3) dynamically size the cache
4) react to the buffer full condition by forcing a prune of the cache.

option 1 combined with option 4 is probably the least intrusive.

**Comment by dglo** [comment]
[tbendfelt on 2018-02-27 16:15:19]
I opted for solution number 4 since the only option for a buffer increase was from 512MB to 1GB.  The overflows are so rare (flasher runs) that in the worst case we will see an overflow warning in the log every minute during a high-rate flasher run.

svn log -v -r16925
------------------------------------------------------------------------
r16925 | bendfelt | 2018-02-27 16:11:46 -0600 (Tue, 27 Feb 2018) | 1 line
Changed paths:
   M /projects/StringHub/trunk/src/main/java/icecube/daq/performance/binary/store/impl/SplitStore.java
   M /projects/StringHub/trunk/src/test/java/icecube/daq/performance/binary/store/impl/SplitStoreTest.java

Issue 8338: Handle an in-memory cache overflow by clearing the cache and retrying the write.
------------------------------------------------------------------------
