### ISSUE TITLE
[jacobsen on 2007-06-29 13:34:12] : pDAQ: StringHub - still drops DOMs due to timeout/interruptExceptions

### ISSUE THREAD

**Issue by dglo** [dglo/StringHub#43]
See notes

**Comment by dglo** [comment]
[jacobsen on 2007-06-29 13:35:04]
From: 	  john@mail.npxdesigns.com
	Subject: 	Still dropping
	Date: 	June 29, 2007 9:27:05 AM CDT
	To: 	  daq-dev@icecube.wisc.edu
	Reply-To: 	  john@mail.npxdesigns.com

Dropped DOMs summary for Highland-09:

2/5 runs had a dropped DOM.  Details follow.  I will look into causes today.

Run    Dropped DOMs
108816     -
    17     -
    18     29-34 (40A, Telephonophobia)
    19     -
    20     39-04 (01A, Trichopathophobia [fear of hair])

Exception details for 29-34:
stringHub STDERR-DataCollector-40A ERROR [Fri Jun 29 00:45:37 UTC 2007]java.nio.channels.ClosedByInterruptException
stringHub STDERR-DataCollector-40A ERROR [Fri Jun 29 00:45:37 UTC 2007]	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:184)
stringHub STDERR-DataCollector-40A ERROR [Fri Jun 29 00:45:37 UTC 2007]	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:150)
stringHub STDERR-DataCollector-40A ERROR [Fri Jun 29 00:45:37 UTC 2007]	at icecube.daq.domapp.DOMIO.recv(DOMIO.java:71)
stringHub STDERR-DataCollector-40A ERROR [Fri Jun 29 00:45:37 UTC 2007]	at icecube.daq.domapp.DOMApp.transitionToDOMApp(DOMApp.java:578)
stringHub STDERR-DataCollector-40A ERROR [Fri Jun 29 00:45:37 UTC 2007]	at icecube.daq.domapp.DataCollector.softbootToDomapp(DataCollector.java:770)
stringHub STDERR-DataCollector-40A ERROR [Fri Jun 29 00:45:37 UTC 2007]	at icecube.daq.domapp.DataCollector.runcore(DataCollector.java:794)
stringHub STDERR-DataCollector-40A ERROR [Fri Jun 29 00:45:37 UTC 2007]	at icecube.daq.domapp.DataCollector.run(DataCollector.java:697)
stringHub icecube.daq.domapp.DataCollector-DataCollector-40A ERROR [Fri Jun 29 00:45:37 UTC 2007]Intercepted error in DataCollector runcore: java.nio.channels.ClosedByInterruptException

Exception details for 39-04:
stringHub icecube.daq.domapp.DataCollector-DataCollector-01A ERROR [Fri Jun 29 01:00:18 UTC 2007]Timeout on trial 0 getting DOM ID
icecube.daq.domapp.MessageException: java.nio.channels.ClosedByInterruptException
 	at icecube.daq.domapp.DOMApp.sendMessage(DOMApp.java:339)
 	at icecube.daq.domapp.DOMApp.sendMessage(DOMApp.java:289)
 	at icecube.daq.domapp.DOMApp.getMainboardID(DOMApp.java:183)
 	at icecube.daq.domapp.DataCollector.runcore(DataCollector.java:795)
 	at icecube.daq.domapp.DataCollector.run(DataCollector.java:697)
Caused by: java.nio.channels.ClosedByInterruptException
 	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:184)
 	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:150)
 	at icecube.daq.domapp.DOMIO.recv(DOMIO.java:71)
 	at icecube.daq.domapp.DOMApp.sendMessage(DOMApp.java:322)
 	... 4 more

stringHub STDERR-DataCollector-01A ERROR [Fri Jun 29 01:00:18 UTC 2007]java.lang.InterruptedException: sleep interrupted
stringHub STDERR-DataCollector-01A ERROR [Fri Jun 29 01:00:18 UTC 2007]	at java.lang.Thread.sleep(Native Method)
stringHub STDERR-DataCollector-01A ERROR [Fri Jun 29 01:00:18 UTC 2007]	at icecube.daq.domapp.DataCollector.softbootToDomapp(DataCollector.java:731)
stringHub STDERR-DataCollector-01A ERROR [Fri Jun 29 01:00:18 UTC 2007]	at icecube.daq.domapp.DataCollector.runcore(DataCollector.java:794)
stringHub STDERR-DataCollector-01A ERROR [Fri Jun 29 01:00:18 UTC 2007]	at icecube.daq.domapp.DataCollector.run(DataCollector.java:697)
stringHub icecube.daq.domapp.DataCollector-DataCollector-01A ERROR [Fri Jun 29 01:00:18 UTC 2007]Intercepted error in DataCollector runcore: java.lang.InterruptedException: sleep interrupted

**Comment by dglo** [comment]
[jacobsen on 2007-06-29 14:16:47]
Sending        src/main/java/icecube/daq/domapp/DataCollector.java
Transmitting file data .
Committed revision 1687.

**Comment by dglo** [comment]
[dglo on 2007-06-29 14:28:05]
-- Fix and comment previous commit
Sending        src/main/java/icecube/daq/domapp/DataCollector.java
Committed revision 1688.

**Comment by dglo** [comment]
[jacobsen on 2007-07-05 18:52:18]
DataCollector to rev 1706, 1707.

**Comment by dglo** [comment]
[jacobsen on 2007-07-05 18:58:53]
Sending        src/main/java/icecube/daq/domapp/DataCollector.java
Transmitting file data .
Committed revision 1708.

**Comment by dglo** [comment]
[jacobsen on 2007-07-05 19:31:06]
1708 seems to work (FINALLY) on SPS
